max_width = 100

fn_call_width = 100 #60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 0 #35
array_width = 60
chain_width = 80 #60
single_line_if_else_max_width = 50

#blank_lines_upper_bound = 3
#format_strings = true
#imports_layout = "Vertical"
#struct_lit_single_line = false
#tab_spaces = 3
#wrap_comments = true
